version: '3.8'

services:
  app:
    build: .
    container_name: order-book-api
    restart: always
    entrypoint: [ "/wait-for-it.sh", "dpg-cufb2u5umphs73b16oeg-a.oregon-postgres.render.com", "5432", "--", "java", "-jar", "app.jar" ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cufb2u5umphs73b16oeg-a.oregon-postgres.render.com:5432/order_book_42al
      SPRING_DATASOURCE_USERNAME: orde_book_user
      SPRING_DATASOURCE_PASSWORD: wh9W9IbJBSjU0JyiwkTp8q2FFlQsI0ii
    ports:
      - "8080:8080"

volumes:
  mysql_data:
